# appveyor.yml
version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\adnvilla\patrician

environment:
  GOPATH: c:\gopath

before_test:
  - go vet ./...

build_script:
  - go test -v ./...
