build_cloud: docker

environment:
  matrix:
  - job_name: Build
    docker_image: golang:1.11
for:
-
  matrix:
    only:
      - job_name: Build
  build_script:
  - echo This is a build stage!
