# appveyor.yml
version: "{build}"

clone_folder: c:\gopath\src\github.com\adnvilla\patrician

services:
  - mysql

environment:
  GOPATH: c:\gopath

before_test:
  - go vet ./...

build_script:
  - go test -v ./...
