openapi: 3.0.3
info:
  title: Patrician API
  version: 1.0.0
paths:
  /cities:
    get:
      summary: List available cities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cities'
  /commodities:
    get:
      summary: List commodities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commodities'
  /distances:
    get:
      summary: List distances between cities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distances'
  /city/{name}/commodities:
    get:
      summary: Get city commodities
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commodities'
    post:
      summary: Bulk update commodities in a city
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommoditiesInput'
      responses:
        '200':
          description: updated
          content:
            text/plain:
              schema:
                type: string
  /city/{name}/commodity:
    post:
      summary: Update single commodity in a city
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommodityInput'
      responses:
        '200':
          description: updated
          content:
            text/plain:
              schema:
                type: string
  /city/{name}/stock:
    get:
      summary: Get stock for a city
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
  /city/{name}/supply/{city}:
    get:
      summary: Get supply from another city
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
        - in: path
          name: city
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
components:
  schemas:
    CommodityInput:
      type: object
      properties:
        name:
          type: string
        buy:
          type: integer
        sell:
          type: integer
        production:
          type: integer
        consumption:
          type: integer
      required: [name, buy, sell, production, consumption]
    CommoditiesInput:
      type: object
      properties:
        commodities:
          type: array
          items:
            $ref: '#/components/schemas/CommodityInput'
      required: [commodities]
    Commodity:
      allOf:
        - $ref: '#/components/schemas/CommodityInput'
    MarketHall:
      type: object
      properties:
        Commodities:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Commodity'
    City:
      type: object
      properties:
        Name:
          type: string
        MarketHall:
          $ref: '#/components/schemas/MarketHall'
    Cities:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/City'
    Commodities:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Commodity'
    Distances:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: number
    Stock:
      type: object
      additionalProperties:
        type: integer
